# Generated by Django 6.0.1 on 2026-02-05 01:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('target_sessions', models.PositiveIntegerField(default=0)),
                ('sessions_completed', models.PositiveIntegerField(default=0)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_fat_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('resting_heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('mood', models.PositiveSmallIntegerField(default=50)),
                ('notes', models.TextField(blank=True)),
                ('emotion_tags', models.JSONField(blank=True, default=list)),
                ('next_step', models.CharField(blank=True, max_length=255)),
                ('success', models.BooleanField(default=False)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('goal_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('training_style', models.CharField(blank=True, max_length=100)),
                ('habit_frequency', models.CharField(blank=True, max_length=100)),
                ('emotional_tone', models.CharField(blank=True, max_length=100)),
                ('intentions', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=200)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('heart_rate_avg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heart_rate_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heart_rate_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('intensity', models.PositiveSmallIntegerField(default=50)),
                ('sets_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reps_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('steps', models.PositiveIntegerField(blank=True, null=True)),
                ('wearable_source', models.CharField(choices=[('manual', 'Manual'), ('apple_health', 'Apple Health'), ('google_fit', 'Google Fit'), ('fitbit', 'Fitbit'), ('garmin', 'Garmin')], default='manual', max_length=32)),
                ('wearable_device_id', models.CharField(blank=True, max_length=120)),
                ('recovery_notes', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
    ]
